# Generated by Django 2.2.7 on 2019-12-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=8)),
                ('user_email', models.TextField()),
                ('user_phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
